-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/5QBaql
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/5QBaql
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "NHES_19_PFI" (
    "id" varchar   NOT NULL,
    "ALLGRADEX" int,
    "SEGRADES" int,
    "CENREG" int,
    "SCH_TYPE" int,
    "EDCPUB" int,
    "EDCCAT" int,
    "EDCREL" int,
    "EDCPRI" int,
    "EDCINTK12" int,
    "EDCHSFL" int,
    "DISTASSI" int,
    "SCHRTSCHL" int,
    "SCHLMAGNET" int,
    "SPBSCH" int,
    "SOTHRSCH" int,
    "STUTR" int,
    "SOTHSCH" int,
    "SEENJOY" int,
    "SEABSNT" int,
    "FCSCHOOL" int,
    "FCTEACHR" int,
    "FCSTDS" int,
    "FCSUPPRT" int,
    "FHHOME" int,
    "FHWKHRS" int,
    "FOSTORY2X" int,
    "FOCRAFTS" int,
    "FOGAMES" int,
    "FOBUILDX" int,
    "FOSPORT" int,
    "FORESPON" int,
    "FOHISTX" int,
    "FODINNERX" int,
    "FOLIBRAYX" int,
    "FOBOOKSTX" int,
    "FOCONCRTX" int,
    "FOMUSEUMX" int,
    "FOZOOX" int,
    "FOGROUPX" int,
    "FOSPRTEVX" int,
    "HHENGLISH" int,
    "CSPEAKX" int,
    "HHTOTALXX" int,
    "HHPRTNRSX" int,
    "P1REL" int,
    "P1SEX" int,
    "P1MRSTA" int,
    "P1AGE" int,
    "P2GUARD" int,
    "P2AGE" int,
    "P2REL" int,
    "P2SEX" int,
    "P2MRSTA" int,
    "PAR1EMPL" int,
    "PAR1FTFY" int,
    "PAR2FTFY" int,
    "NUMSIBSX" int,
    "TTLHHINC" int,
    "OWNRNTHB" int,
    "HVINTSPHO" int,
    "HVINTCOM" int,
    "INTACC" int,
    "CHLDNT" int,
    "LRNCOMP" int,
    "LRNTAB" int,
    "LRNCELL" int,
    CONSTRAINT "pk_NHES_19_PFI" PRIMARY KEY (
        "id"
     )
);
